name: nearscaff
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10,<3.13
  - networkx>=3
  - minimap2>=2.24
  - miniprot>=0.13
  - samtools>=1.15
  - jellyfish>=2.3
  - numpy
  - scipy
  - scikit-learn
  - pip
  - pip:
      - .
